<?php
    $ds = array(
        1 => ["hinh/c1.jpg","Other","Sport","Acura NSX 2020",159402,"Like the original that went out of production in 2005, today's Acura NSX aims to deliver supercar looks and performance in an everyday livable package. Indeed, there's plenty of stretch-out space for two passengers, and one needn't fold themselves into an origami crane to get into and out of it. Behind those passengers sits a twin-turbocharged 3.5-liter V-6 that, along with an electric motor, powers the rear wheels; it's assisted by two more electric motors that individually power each front wheel for precise power delivery while turning. Total output is a healthy 573 horsepower. Even so, the NSX is less hardcore than many other mid-engined sports cars at this price point. "],
        2 => ["hinh/c2.jpg","Chevrolet","Muscle","Chevrolet Camaro ZL1 2022",66045,"The 2022 Chevy Camaro ZL1 isn't the most powerful muscle car, but when it comes to driver involvement and value for the performance, it's unbeatable. It's also on our 2022 Editors' Choice list. The bow-tie boys stuff a 650-hp supercharged V-8 between the ZL1's fenders and offer a satisfying manual transmission or a snappy 10-speed automatic. Sure, the Ford Mustang Shelby GT500 packs a 760-hp V-8 and its own incredible track capabilities, but it doesn't offer a stick-shift or a convertible body style. Plus, unlocking the Shelby's full potential costs considerably more than the Camaro's transformative 1LE package. While a ZL1 1LE has the hardware and tuning to slay some six-figure cars around a racetrack, its ride will be too harsh for anyone who isn't a glutton for punishment. And, as with every Camaro, the ZL1's outward visibility is compromised and the interior materials are unimpressive. Still, the 2022 Camaro ZL1 makes its driver feel like a king and lords over its fiercest rivals."],
        3 => ["hinh/c3.jpg","Other","Muscle","Ford Mustang EcoBoost 2022",28865,"Whether it's used for top-down trips on the Sunset Strip or track time at Lime Rock, there's a 2022 Ford Mustang for most every lifestyle and personality. With countless appearance packages, notable performance-enhancing options, and coupe or convertible body styles, it can be highly personalized. Power comes from a punchy turbo four or a mighty 5.0-liter V-8; both engines feed the rear wheels through an engaging manual transmission or a terrific 10-speed automatic. While all models are fun to drive, Ford offers myriad packages to up the excitement, culminating in the track-focused Mach 1. Even the most aggressive Mustang (excluding the 760-hp Shelby GT500) can be driven every day, and it has a roomier back seat and better outward visibility than the Chevy Camaro. When it comes to pony cars, there's none better than the 2022 Mustang, which is why it's on our Editors' Choice list."],
        4 => ["hinh/c4.jpg","Other","Muscle","Dodge Charger SRT Hellcat 2022",79595,"The 2022 Dodge Charger SRT Hellcat, which comes standard with 717 horsepower, is one helluva family sedan. Not only are its big back seat and trunk great for taking more than two people on trips or just out to lunch, it accelerates so ferociously that the same passengers will be cussing up a storm or asking for an airsick bag­ or both. For an extra dose of \"hold onto your butts,\" the Redeye model boasts a ridiculous 797 horses and will hit 60 mph in 3.5 seconds on its way to a claimed 203-mph top speed. While all that power might be too much for some, the widebody-only Charger actually handles surprisingly well for its size. Just expect better communication from your in-laws than from its steering. Compared with high-performance, six-figure luxury cars such as the Mercedes-AMG GT63 S and Porsche Panamera Turbo S, the 2022 Charger SRT Hellcat is a great value. Too bad its interior looks like it came from a car that costs less than half its nearly $75,000 starting price—which it does."],
        5 => ["hinh/c5.jpg","BMW","Sport","BMW M8 Competition 2023",131995,"The mind-bending acceleration delivered by the BMW M8’s 617-hp twin-turbo V-8 is strong enough to get the car to 60 mph in just 2.5 seconds. At 10.7 seconds the M8 reaches 129 mph as it covers a quarter-mile of road. That’s quicker than a 710-hp Ferrari 488 Pista from something with a rear seat weighing more than two tons. Chalk it up to all-wheel drive traction and an overachieving engine. The M8 is crazy-fast, but its smooth delivery of felony speeds and its bolted-to-the-road stability make driving fast feel almost responsible. Available as both a coupe and convertible (the four-door M8 Gran Coupe is reviewed separately), the M8 cockpit is well-appointed and uses a large infotainment screen to handle navigation or audio selection. However, its rear seat isn’t a practical space. As one of the most affordable cars that will get you into 10-second quarter miles every time you try, the M8 is a big coupe with even bigger performance numbers."],
        6 => ["hinh/c6.jpg","Lamborghini","Sport","Lamborghini Urus 2022",229495,"On paper, the supercar-bred, 641-hp Lamborghini Urus sounds overmatched against the 707-hp, Hellcat-powered Jeep Grand Cherokee Trackhawk. However, only one of these outrageous machines owns the crown as the quickest SUV we've ever run at Virginia International Raceway in our annual Lightning Lap event. For those who couldn’t guess, it's the Lambo, which costs nearly a quarter-million dollars. That's the entry price to own a wildly styled SUV of this pedigree. Along with unbelievable track skills for its size, the Urus offers some things that the Lamborghini Aventador and Huracán don't: a back seat, useable cargo space, and the ability to tow. While its interior craftsmanship isn't as good as its supercar siblings’, and it's the very definition of a gas-guzzler, the 2022 Lamborghini Urus is easily the most badass family hauler on the planet."],
        7 => ["hinh/c7.jpg","Audi","Sport","Audi RS7 2021",115045,"The 2021 Audi RS7 is a wide-bodied, heart-pounding four-door sports car that features a usable back seat and practical hatchback. This all-new RS7 represents the mightiest version of the comparably subdued Audi A7. The RS model wears more aggressive-looking bodywork and has exclusive high-performance equipment that helps it compete with raucous rivals such as the Mercedes-AMG GT63s and Porsche Panamera Turbos."],
        8 => ["hinh/c8.jpg","Other","Sport","Bugatti Chiron 2019",2998000,"Leaving the 99.99 percent in its dust, the Chiron is a 1500-hp smackdown of every hypercar ever produced. The $2,998,000 price tag is a bourgeoisie bargain—hey, it's less than $3 million."],
        9 => ["hinh/c9.jpg","Chevrolet","Sport","Chevrolet Corvette 2023",65595,"With supercar performance, an affordable price tag, and flashy styling, the 2023 Chevrolet Corvette honors the nameplate's decades-old status as an automotive icon—but with a mid-engine twist. The current C8 is the first generation to have its naturally aspirated V-8 engine mounted behind the passenger compartment, which boosts Chevy's halo sports car into the realm of exotic machinery. Its sharp handling and explosive acceleration are a match for sports cars costing tens of thousands more, but it’s also comfortable and refined enough to drive cross-country. The C8 is offered as both a convertible and a coupe, and the hardtop model has a roof panel that can be lifted off to allow the sun to shine in. Its cabin is cozy but comfortable and there's adequate trunk storage for groceries or luggage, making the Corvette an easy sports car to live with on a daily basis. We're charmed by this perennial favorite and we think you will be too."],
        10 => ["hinh/c10.jpg","Other","Muscle","Ford Mustang EcoBoost 2022",28865,"Arguably one of the most recognizable cars of all time, the 2020 Ford Mustang continues to deliver eye-catching style and driving excitement. Its ability to be personalized and performance-enhanced also have endeared Ford's pony car to the public for more than 55 years. While the standard turbocharged four-cylinder might sound like a blasphemous choice for a muscle car, the EcoBoost model is legitimately enjoyable and affordable. The Mustang GT continues to carry the V-8 torch against crosstown rivals from Chevy and Dodge, but it bests them with a better combination of athleticism and livability. Sure, some of the Stang's interior materials are subpar and its back seat is tight, but this legendary muscle car has evolved and consistently lived up to that title."],
        11 => ["hinh/c11.jpg","Chevrolet","Muscle","Chevrolet Camaro 2021",26195,"There's nothing quite like hearing the thrilling timbre of a throbbing exhaust note or feeling the gratifying feedback from a superbly tuned steering system while flying down a twisty road. Few affordable cars offer both these satisfying sensations, but the Chevy Camaro is one of them. It's not focused solely on being loud and going fast, however—even though it does both of those tasks very well. Chevy's two-door pony car comes as a coupe or convertible, and it offers copious features and countless personalization options. While the 650-hp Camaro ZL1 is the most raucous version—and reviewed separately—every model from the base four-cylinder to the V-6 to the V-8 can be enhanced for track duty with the transformational 1LE package. Sure, the interior can feel claustrophobic and has several other quirks, but the 2021 Chevy Camaro is primarily geared towards those who love to drive. Like us."],
        12 => ["hinh/c12.jpg","Audi","Muscle","Audi RS3 2022",59995,"With a potent 401-hp turbocharged five-cylinder engine, the 2022 Audi RS3 is the raciest version of the company's small luxury sedan. Based on the four-door Audi A3 and the sportier S3–but blessed with even more power and enhanced chassis tuning–the new RS variant challenges hi-po rivals such as the BMW M2 coupe and Mercedes-AMG CLA45 sedan. However, the RS3's unusual engine gives it one of the most distinct soundtracks in its class. The Audi's sharply creased sheetmetal as well as its stylish, nicely appointed interior help it appeal to audiences who appreciate sportiness as much as luxuriousness."],
        13 => ["hinh/c13.jpg","Other","Muscle","Alfa Romeo Stelvio 2023",47795,"The Alfa Romeo Stelvio isn’t just a pretty face. Named after the tortuously serpentine Stelvio Pass in northern Italy—one of the country’s most revered driver’s roads—this compact luxury SUV has a chassis that sticks to curvy switchbacks like Pecorino Romano to spaghetti. Base Sprint models come with rear-wheel drive, and all-wheel drive is standard on all other trim levels—but every Stelvio gets a zesty 280-hp turbocharged four-cylinder and eight-speed automatic transmission. We recommend shopping the 505-hp Quadrifoglio model, reviewed separately, for a Stelvio that’ll light up your synapses. The standard model’s interior makes a good attempt at the luxury side of the business; however, its 8.8-inch infotainment touchscreen is one of the smallest in a segment of more generously-sized offerings. A small-ish back seat and cargo area make the Stelvio a better choice for goers instead of stowers, but its iconic take on the traditional Alfa grille makes mistaking it for rival SUVs like the BMW X3 or Porsche Macan impossible."],
        14 => ["hinh/c14.jpeg","BMW","Muscle","BMW i4 2023",51400,"The all-electric BMW i4 sedan is an important piece of BMW’s expanding EV portfolio. It offers the style of the 4-series Grand Coupe with a battery powertrain and highly refined road manners. There are three distinct i4 flavors: The first two use are single motor rear-drive, with the eDrive35 offering 281 horsepower and 260 miles of EPA range, while the eDrive40, produces 335 horsepower with an estimated 300 miles of driving. That figure drops to 245 miles in the spicy, all-wheel-drive, 536-hp i4 M50. The latter drives like a better-riding M3, which is a mega compliment. The M50 reaches 60 mph in just 3.3 seconds, 0.2 seconds than an M3 Competition, and it can jump from 50 to 70 mph in just 2.0 seconds—0.7 seconds quicker than the Bimmer. When not performing ab-exercising acceleration runs, the i4 is an admirable daily driver. Although it lacks the steering feedback we prefer in other M cars, it’s an exciting and refined sedan with a supple ride and deeply satisfying sports-sedan handling. "],
        15 => ["hinh/c15.jpg","Other","Sport","Maserati MC20 2022",216995,"Maserati has been teasing us with the new MC20 mid-engine sports car for some time now, and we've finally driven this sweet little cannoli and sampled its novel 621-hp twin-turbo V-6. The MC20 is offered as a two-seater coupe with a minimalist cabin that's focused on the driver; a convertible is expected to join the lineup later and eventually an electric MC20 will reach production too. A collaboration with motorsport engineering company Dallara has resulted in a carbon-fiber structure with aluminum subframes for the suspension and powertrain. This construction minimizes weight, which sets the MC20 up for performance-related success."],
        16 => ["hinh/c16.jpg","Chervolet","Sport","Chevrolet Corvette Z06 2023",106395,"The 2023 Chevy Corvette Z06 is expected to elevate the iconic nameplate into territory occupied by exotics from Ferrari and Lamborghini. With the engine now located behind the driver, it already looks unlike any Z06 seen before. Not only is it considerably wider than the regular Corvette Stingray, it boasts bigger air intakes and a unique rear wing. Thanks to a flat-plane crankshaft, the new Z06's naturally aspirated 5.5-liter V-8 also won't sound like any Vette that's come before. While it inherits the best amenities and technology from the Stingray, its performance and handling will be heightened and sharpened. Chevy switched to a mid-engine layout to make the C8 Corvette a supercar that more folks can afford, and the 2023 Corvette Z06 promises to embarrass more than a few people driving insanely expensive supercars when they meet at a racetrack."],
        17 => ["hinh/c17.jpg","Chervolet","Sport","Chevrolet Blazer EV 2024",44995,"When Chevrolet brought back the Blazer as a two-row mid-size crossover in 2019, fans of the original who were hoping for an off-road-ready SUV were vocal with their disappointment. Now comes another surprise wearing a Blazer badge, as Chevy takes the SUV with the storied name into the electric realm of autodom for 2024. The gas-free version is called the Blazer EV, and if you’re disappointed by the Blazer’s electrification take solace in the SS trim, which offers 557 horsepower and is said to be capable of hitting 60 mph in less than four seconds. While the SS seems tailormade to take on the likes of the Ford Mustang Mach-E GT and the Tesla Model Y Performance, three other more affordable, less powerful models will be available as well. The Blazer EV uses General Motors’ Ultium battery technology, and the model with the most range will be the RS trim, which Chevy says will go about 320 miles on a charge."],
        18 => ["hinh/c18.jpg","Other","Sport","Maserati MC20 2023",217000,"With a carbon-fiber structure, a hellacious 621-hp twin-turbo V-6, and neck-wrenching cornering power, the 2023 Maserati MC20 is an exotic street car that smacks you in the face with a race-car driving experience. Its slinky Italian-esque supercar shape and butterfly-style doors have passers-by staring at it just like they do at Ferraris and Lamborghinis. The new Cielo Spyder convertible allows for open-air cruising—and being seen—at the touch of a button. Like many a supercar, though, the MC20 comes with its own specific set of drawbacks. While its suspension is compliant enough for the occasional road trip, the car’s cargo capacity is miniscule; you’ll need your administrative assistant to follow you with your luggage. Maserati also offers virtually no driver-assistance features on the MC20; there’s no adaptive cruise control or lane-keeping assist. So be it. From the view out the windshield to its cacophony of wild engine sounds to its butt-kicking performance, the MC20 is made for hard-core enthusiast drivers with the money to indulge themselves in a car with overwhelming character. "]
    );
    $severname = "localhost";
    $username = "root";
    $password = "";
    $dbname = "users_account";
    $sql2 ="";
    $conn = new mysqli($severname,$username,$password,$dbname);
    if($conn->connect_error){
        die("Connection failed".$conn->connect_error);
    };
    for($i = 1; $i <= count($ds);$i++){
        if($i == count($ds)){
            $sql2 .= "INSERT INTO Cars (img, brand, class, name, price)
        VALUES ('{$ds[$i][0]}', '{$ds[$i][1]}', '{$ds[$i][2]}','{$ds[$i][3]}',{$ds[$i][4]})";
        }else{
        $sql2 .= "INSERT INTO Cars (img, brand, class, name, price)
        VALUES ('{$ds[$i][0]}', '{$ds[$i][1]}', '{$ds[$i][2]}','{$ds[$i][3]}',{$ds[$i][4]});";
        }   
    };
    echo $sql2;
    if ($conn->multi_query($sql2) === TRUE) {
        $tb= "New records created successfully";
    } else {
        $tb= "Error: " . $sql2 . "<br>" . $conn->error;
    };
    // $conn->close();
?>